const locatorsConsole = {
  authPage: {
    inputLogin: '//input[@id="userName"]',
    buttonNext: '//button[text()=" Next"]',
    inputPassword: '//input[@type="password"]',
    buttonSignIn: '//button[@type="submit" and text() = "Sign in"]',
  },
  learningPlan: {
    addComponentBtn: '//button/span[text()="Add Component"]',
  },
  addFileEvidence: {
    evidenceTypeSelect: '//span[@id="k-3cd98268-4f68-432c-af54-6558362ba2a9"]/span[@class="k-input"]',
    selectFileButton: '//div[@aria-label="Select file..."]',
    saveBtn: '//button/span[text()="Save"]',
  },
  header: {
    menuItemReviews: '//a/span/label[text()="Reviews"]',
    userSettingIcon: '//button[@id="user-settings"]',
    switchBtn: '//a[contains(text(), "Switch to Aptem Classic")]',
  },
  navigatePanel: {
    dashBoard: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/caseload-dashboard"]',
    learners: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/learners"]',
    jobFinder: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/jobfinder"]',
    // jobFinder: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/jobfinder"]',
    signatures: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/signatures"]',
    tasks: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/tasks"]',
    messages: '//a[@href="/pwa/messages"]',
    adviceCentre: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/advice-centre"]',
    BPI: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/report"]',
    resourceCentre: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/resource-centre"]',
    registrationCertification: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/registration-certification"]',
    tenantSettings: '//menu[@id="menu-learner"]/nav/ul/li/a[@href="/pwa/tenant-settings"]',
  },
  learnersGrig: {
    filtersButton: '//button[@routerlink="/learners/filter"]',
    searchInput: '//input[contains(@class,"input-icon-text k-textbox")]',
    // searchInput: '//input[@id="learnerSearch"]',
    foundUser: '//tr/td//span[text()="Learner10 CreatedByCSV"]',
    sidePanelFilters:{
      container:  '#sidepanel-container',
      groupsLabel: '//label[text()="Groups"]',
      groupNameContainer: '//nz-tree-node-title/span',
    },
  },
  learnerDashboard: {
    learnerProfileButton: '//button[text()=" Learner Profile "]',
    addProgrammeButton: '//a/span[text()="Add Programme Details "]',
  },
  reviewGrid: {
    mainTitle: '//h1',
    plannedReviewButton: '//button[text()="Planned "]',
    // plannedReviewButton: '//button[text()="Completed "]',
    createReviewButton: '//button[@routerlink="planned-review/create"]/svg-icon/../span[text()="Create Review"]',
    row: {
      firstRow: '//tbody/tr[position()=1]',
      reviewName: '//tbody/tr[position()=1]//td[position()="2"]/p',
      reviewType: '//tbody/tr[position()=1]//td[position()="2"]/span',
      plannedDate: '//tbody/tr[position()=1]//td[position()="3"]',
      reviewer: '//tbody/tr[position()=1]//td[position()="4"]',
      status: '//tbody/tr[position()=1]//td[position()="5"]//span',
      schedule: '//tbody/tr[1]//td[5]//a',
      startReviewButton: '//tbody/tr[position()=1]//button[text()="Start"]',
    },
    dropDownMenu: {
      openDDMenuButton: '//tbody/tr[position()=1]//button[@aria-controls="dropdown-menu"]',
      editButton: '//li/a//span[text()="Edit"]',
      deleteButton: '//li/a//span[text()="Delete"]',
    },
    createReviewForm: {
      cancelButton: '//button[@aria-label="Close Button"]',
      mainTitle: '//h1',
      nameInput: '//input[@id="reviewNameInput"]',
      program: '//*[@formcontrolname="subProgrammeId"]',
      reviewType: '//*[@formcontrolname="reviewType"]',
      evidenceRequired: '//input[@id="evidenceRequiredInput"]',
      completeBy: '//*[@formcontrolname="lengthUnit"]',
      reviewer: '//*[@formcontrolname="reviewerId"]',
      uploadFile: '//input[@type="file"]',
      createTaskFor: '//*[@formcontrolname="reviewerId"]',
      useZoom: '//input[@id="isZoomUsedInput"]',
      saveButton: '//button[text()="Save"]',
      // cancelButton: '//button[text()="Cancel"]',
    },
    scheduledAssistant: {
      backButton: '//button[@aria-label="back"]',
      addCalendarsButton: '//div[@class="d-flex"]/following-sibling::button[1]',
      addCalendarsButton2: '//add-calendar//button[text()="Add Calendars"]',
      searchByName: '//input[@id="learnerSearch"]',
      groupFilter: 'groups-filter',
      groupFilterCheckbox: '//nz-tree-node-checkbox[contains(@class,"ant-select-tree-checkbox")]',
      groupFilterCheckboxChecked: '//nz-tree-node-checkbox[contains(@class,"ant-select-tree-checkbox-checked")]',
      adminListItem: '//img[@alt="user"]/following-sibling::span',
      checkBox: '//add-calendar//tr[1]/td[1]/input',
      // currentCaseload: '//tr[${row}]//div/div[2]/span',
      // availableCapacity: '//tr[${row}]//div/div[3]/span',
    },
  },
};

export { locatorsConsole };
