export const menuAdminNav = {
  learnerProfileLink: '//menu-admin//button/h6',
  learnerDashboardLink: '//menu-admin//nav/ul/li/a//label[text()="Dashboard"]',
  learnerLearningPlanLink: '//menu-admin//nav/ul/li/a//label[text()="Learning Plan"]',
  learnerCalendarsLink: '//menu-admin//nav/ul/li/a//label[text()="Calendars"]',
  learnerMessagesLink: '//menu-admin//nav/ul/li/a//label[text()="Messages"]',
  learnerReviewsLink: '//menu-admin//nav/ul/li/a//label[text()="Reviews"]',
  editButton: '//menu-admin//nav/ul/li/button',
  learnersTrackersLink: '//menu-admin//nav/ul/li/a//label[text()="Trackers"]',
  learnersJobFinderLink: '//menu-admin//nav/ul/li/a//label[text()="Job Finder"]',
  learnersCVsLink: '//menu-admin//nav/ul/li/a//label[text()="CVs"]',
  learnersDocumentsLink: '//menu-admin//nav/ul/li/a//label[text()="Documents"]',
  learnersSkillsRadarLink: '//menu-admin//nav/ul/li/a//label[text()="Skills Radar"]',
  learnersNotesLink: '//menu-admin//nav/ul/li/a//label[text()="Notes"]',
  learnersCallLink: '//menu-admin//nav/ul/li/ul//button//label[text()="Call"]',
}