export const createReviewForm = {
  reviewNameInput: 'input[type="text"]',
  programDD: '//label[text()=" Programme"]/..//kendo-dropdownlist',
  reviewTypeDD: '//label[text()=" Review Type "]/../kendo-dropdownlist',
  completionModeDD: '//label[text()=" Completion mode "]/..//kendo-dropdownlist',
  evidenceRequiredCheckBox: '//label[text()="Evidence required"]/../input',
  completedByDD: '//label[text()=" Complete by"]/..//kendo-dropdownlist',
  completedByInput: '//input[@role="spinbutton"]',
  reviewerDD: '//label[text()=" Reviewer"]/..//kendo-dropdownlist',
  uploadFileBtn: '//label[text()=" Upload file "]/..//div[@role="button"]',
  scheduleReviewCheckBox: '//label[text()=" Schedule Review now "]/../input',
  reviewStatusBadge: '//review-status-badge',
  reviewDateLabel: '//label[text()=" Review date"]',
  reviewDateInput: '//label[text()=" Review date"]/../kendo-datepicker',
  startTimeLabel: '//label[text()="Start Time"]',
  startTimeInput: '//label[text()="Start Time"]/../kendo-timepicker',
  endTimeLabel: '//label[text()="End Time"]',
  endTimeInput: '//label[text()=" Schedule Review now "]/../../..//label[text()="End Time"]/../kendo-timepicker',
  useZoomCheckBox: '//label[text()=" Use Zoom "]/../input',

}